### ISSUE TITLE
[BUG] Images are missing SSH

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/docker#214]
**Describe the bug**

It is not possible to use SSH from within the RAPIDS container.

**Steps/Code to reproduce bug**

```
$ ssh
bash: ssh: command not found
```

**Expected behavior**

SSH is a standard utility and should be available in the RAPIDS environment. Especially if the user needs to connect to external systems.

**Comment by ajschmidt8** [comment]
@jacobtomlinson, what's the use case for this? any reason why it couldn't be installed at runtime?

**Comment by jacobtomlinson** [comment]
I totally appreciate that, but SSH is a pretty standard utility, and small too.

The use case for this was needing to port forward a Dask cluster connection from another machine. 

To be honest I was just surprised that it wasn't already included.

**Comment by ajschmidt8** [comment]
Yes, it is small. And standard too. But it doesn't seem uncommon for other images to not include it (see the Ubuntu image below). I'm hesitant to suggest that we should add it to our images since this is only the first time it's been requested and since it can be easily installed at runtime. Can you use the `EXTRA_APT_PACKAGES` environment variable that we introduced previously? That seems like a perfect use case for this.

![image](https://user-images.githubusercontent.com/7400326/110173068-1db2f580-7dcc-11eb-988c-6ba3ff63134d.png)

**Comment by jacobtomlinson** [comment]
I think given that the RAPIDS image is intended to be used as an interactive Data Science environment where users will be actively working it makes sense to include a few more standard Linux utilities.

The base ubuntu image is typically not intended for interactive use in the same way, so I don't think it's a fair comparison.

**Comment by ajschmidt8** [comment]
Ok. Sounds like this would benefit RAPIDS users, so if you open a PR for this, I will review/approve and merge it.

**Comment by jacobtomlinson** [comment]
Thanks @ajschmidt8
