### ISSUE TITLE
[BUG] notebooks frozen at branch=0.16 in runtime image

### ISSUE THREAD

**Issue by mattf** [rapidsai/docker#325]
**Describe the bug**
the notebooks are frozen at branch=0.16

this is an issue because apis have changed since 0.16, e.g. add_column and set_index takes a keys param instead of index

this reproduces in 0.18 and 0.19 but not nightly (currently 0.20). it should be verified fixed with the final 21.06 release images.

**Steps/Code to reproduce bug**
```
$ docker run rapidsai/rapidsai:0.18-cuda11.0-runtime-ubuntu18.04 head -n4 notebooks/.gitmodules
[submodule "repos/cudf"]
	path = repos/cudf
	url = https://github.com/rapidsai/cudf.git
	branch = branch-0.16

$ docker run rapidsai/rapidsai:0.19-cuda11.2-runtime-ubuntu20.04-py3.8 head -n4 notebooks/.gitmodules
[submodule "repos/cudf"]
	path = repos/cudf
	url = https://github.com/rapidsai/cudf.git
	branch = branch-0.16
```
this does not reproduce for nightly images
```
$ docker run rapidsai/rapidsai-nightly:cuda11.2-runtime-ubuntu20.04 head -n4 notebooks/.gitmodules
[submodule "repos/cudf"]
	path = repos/cudf
	url = https://github.com/rapidsai/cudf.git
	branch = branch-0.20
```

**Expected behavior**
i expect to see a branch equal to the version of the container

**Additional context**
the .gitmodules in notebooks is updated appropriately for each new release, see https://github.com/rapidsai/notebooks/commits/branch-21.06/.gitmodules

**Comment by ajschmidt8** [comment]
Hey @mattf, thanks for bringing this to our attention. Our stable Docker images clone the `main` branch from our [notebooks repo](https://github.com/rapidsai/notebooks/tree/main) and it seems that we haven't been keeping that branch up to date as we should. I will make our team aware of this to ensure that it doesn't happen again during the `21.06` release.

Since there is no further action required for this issue, I will close this. Thanks again.
