### ISSUE TITLE
Adding Requirement to rapidsai

### ISSUE THREAD

**Issue by oscaranderssons** [rapidsai/docker#61]
I am having issues adding python libraries to my docker file when I use rapidsai as the base image. 
This is what my docker image looks like:

FROM rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04-py3.7
COPY * /ai/
WORKDIR /ai/

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

CMD ["python3", "test.py"]

And my requirements.txt file looks like this:

kivy
beautifulsoup4
sympy

my test.py file:

import kivy
print('Kivy version: ', kivy.__version__)

import sympy
print('Sympy version: ', sympy.__version__)

import platform
print('Python version: ', platform.python_version())

The result I get after building and running my docker image is:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import kivy
ModuleNotFoundError: No module named 'kivy'

And I get similar results for the other libraries in my requirements.txt file. Why does my docker image build and install the libraries but it doesn't know it is installed when I am trying to run the image. How am I supposed to add python libraries that I need to the rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04-py3.7 image?

**Comment by ajschmidt8** [comment]
@oscaranderssons, because of the [entrypoint](https://github.com/rapidsai/docker/blob/branch-0.15/generated-dockerfiles/ubuntu18.04-runtime.Dockerfile#L63) used in our Dockerfiles, all `docker run` commands are executed in a `conda` environment named `rapids`. Therefore, you'll need to make sure your `python` dependencies are installed in that environment instead of at the system level. I was able to get your example working with the updated Dockerfile below. Please let me know if this resolves your issue.


```dockerfile
FROM rapidsai/rapidsai-nightly:0.15-cuda10.1-runtime-ubuntu18.04-py3.7
COPY * /ai/
WORKDIR /ai/

RUN source activate rapids && python3 -m pip install --upgrade pip
RUN source activate rapids && python3 -m pip install -r requirements.txt

CMD ["python3", "test.py"]
```

**Comment by ajschmidt8** [comment]
closing this issue given the solution above.
