### ISSUE TITLE
[DOC] - Website configurator is incorrect

### ISSUE THREAD

**Issue by SharplyUnclear** [rapidsai/docker#73]
## Report incorrect documentation
The configurator documentation at https://rapids.ai/start.html#get-rapids is no longer quite correct 
These are tiny points, but might put a newcomer off:

Provide links and line numbers if applicable.
 https://rapids.ai/start.html#get-rapids

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.
The https://rapids.ai/start.html#get-rapids page says "The copied Docker command above should auto-run a notebook server. If it does not, run the following command within the Docker container to launch the notebook server.
bash /rapids/notebooks/utils/start-jupyter.sh
"

**Steps taken to verify documentation is incorrect**
List any steps you have taken:
I can confirm that neither cuda10.2-runtime-ubuntu18.04 or cuda10.2-runtime-ubuntu18.04-py3.7 auto-run a notebook server (they drop you to the command line). 
And the directory for the start_jupyter.sh script is now at /rapids/utils 

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

Correct the the Docker images to auto-run a notebook server and change the documentation so the location of the directory for start_jupyter.sh is /rapids/utils (not the current /rapids/notebooks/utils/start-jupyter.sh)

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.
Current documentation is wrong.

**Describe the documentation you'd like**
Options are laid-out above 

**Steps taken to search for needed documentation**
List any steps you have taken:
Not applicable

**Comment by ajschmidt8** [comment]
@SharplyUnclear, thank you for opening this issue. Previously, our Docker containers would start a `jupyter-lab` server in the background before dropping the user into a `bash` terminal. We've recently made some changes to make that more clear to our end-users (see screenshot below). Additionally, we've updated the documentation site to point to the correct directory, `/rapids/utils/start-jupyter.sh`. 

![image](https://user-images.githubusercontent.com/7400326/89815850-76126500-db13-11ea-9d67-f18a2463999b.png)


I will close this issue since it seems to be complete but feel free to reply here or open a new issue if you notice anything else that's not correct.
