### ISSUE TITLE
[BUG] pytorch is not included even though its used by example notebook

### ISSUE THREAD

**Issue by tomgreen66** [rapidsai/docker#74]
**Describe the bug**
When using the cusignal notebook from a docker container `/rapids/notebooks/cusignal/E2E_Example.ipynb` it tries to import torch which is not installed.

**Steps/Code to reproduce bug**
1. Run docker container `rapidsai_cuda10.1-runtime-centos7` within Singularity.
2. Start Jupyter server with `singularity run --nv rapidsai_cuda10.1-runtime-centos7.sif`
3. Access Jupyter on `localhost:8888`
4. Try running the `cusignal/E2E_Example.ipynb` example.

**Expected behavior**
Notebook completes without failure.

**Environment details (please complete the following information):**
 - Environment location: Singularity on local HPC system
 - Method of cuDF install: Docker container
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
`$ singularity pull docker://nvcr.io/nvidia/rapidsai/rapidsai:cuda10.1-runtime-centos7`
`$ singularity run --nv rapidsai/rapidsai_cuda10.1-runtime-centos7.sif`
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 
[rapids.log](https://github.com/rapidsai/build/files/4440592/rapids.log)

**Additional context**
Using Singularity on HPC so could be issues with that.

**Comment by ajschmidt8** [comment]
@tomgreen66, thanks for bringing this to our attention and apologies for the late reply here. I'm told that we intentionally exclude PyTorch from our images due to its size. However, I just opened a PR to cusignal (https://github.com/rapidsai/cusignal/pull/242) to add both an explanation and a workaround for users who are running this Notebook in our containers.

closing this issue.
